Update Helpdesk for Giza
Joystream/helpdesk pull request #114
Opened 2022-01-20 20:52 UTC by bwhm

Note that for the early birds. you need to switch to the `giza` branch on the [joystream](https://github.com/Joystream/joystream) repo, as we haven't merged to master.

2022-01-26 20:04 UTC, mnaamani requested changes
Awesome job putting this guide together.
Only a couple of typos and had a suggestion for query-node setup. Basically installing latest docker-compose will make instructions much simpler.

One final thought - I think it doesn't make sense for us to require to keep running old sumer query-node just for purpose of getting the initial state of channel and video categories. So we should probably just copy those somewhere and use them in the instructions.

2022-01-26 20:04 UTC, mnaamani commented on tools/query-node/README.md
> +$ export AT_BLOCK_NUMBER=<xxx>
we should probably clarify that this should be the runtime update block number,

2022-01-26 20:04 UTC, mnaamani commented on tools/query-node/README.md
> +yarn build
I don't think this additional build step is necessary

2022-01-26 20:04 UTC, mnaamani commented on tools/query-node/README.md
> +           height: "[<xxx>,<xxx>]"
same about xxxx

2022-01-26 20:11 UTC, bwhm commented on tools/query-node/README.md
> +
Thanks - will add :)

2022-01-26 20:11 UTC, bwhm commented on tools/query-node/README.md
> +$ export AT_BLOCK_NUMBER=<xxx>
Yeah, I had the `<xxx>` to search/replace, but...

2022-01-26 20:12 UTC, bwhm commented on tools/query-node/README.md
> +yarn build
Thanks!

2022-01-26 20:14 UTC, bwhm commented on tools/query-node/README.md
> +$ export AT_BLOCK_NUMBER=<xxx>
...forgot to push!

2022-01-27 12:09 UTC, bwhm commented
@mnaamani 
I think this needs more additions and improvements, but it's a start, so if ok -> merge?

2022-01-27 14:26 UTC, blrhc commented on roles/distributors-lead/README.md
> +A bucket family is a collection of distribution buckets associated with a geographical region (eg. from larger to smaller: World, Europe, Norther Europe, Scandinavia, Norway, Oslo). This is meant to
```suggestion
A bucket family is a collection of distribution buckets associated with a geographical region (eg. from larger to smaller: World, Europe, Northern Europe, Scandinavia, Norway, Oslo). This is meant to reduce latency when serving content.
```

2022-01-27 14:28 UTC, blrhc commented on roles/distributors-lead/README.md
> +Storage and Distribution system is well documented on github. A simple version will be outlined here.
```suggestion
Storage and Distribution system is well documented on GitHub. A simple version will be outlined here.
```

2022-01-27 14:31 UTC, blrhc commented on roles/distributors/README.md
> +To configure SSL-certificates the easiest is to use [caddy](https://caddyserver.com/), but feel free to take a different approach. Note that if you are using caddy for commercial use, you need to acq
```suggestion
To configure SSL-certificates the easiest option is to use [caddy](https://caddyserver.com/), but feel free to take a different approach. Note that if you are using caddy for commercial use, you need to acquire a license. Please check their terms and make sure you comply with what is considered personal use.
```

2022-01-27 14:33 UTC, blrhc commented on tools/query-node/README.md
> +To configure SSL-certificates the easiest is to use [caddy](https://caddyserver.com/), but feel free to take a different approach. Note that if you are using caddy for commercial use, you need to acq
```suggestion
To configure SSL-certificates the easiest option is to use [caddy](https://caddyserver.com/), but feel free to take a different approach. Note that if you are using caddy for commercial use, you need to acquire a license. Please check their terms and make sure you comply with what is considered personal use.
```

2022-01-27 14:34 UTC, blrhc approved these changes
Just very minor typos/style, other than that, very clear AFAIC.

2022-01-27 14:45 UTC, merged