Improvements to Giza
Joystream/helpdesk pull request #116
Opened 2022-01-27 23:21 UTC by bwhm

WIP...

2022-01-27 23:53 UTC, traumschule requested changes
good read

2022-01-27 23:53 UTC, traumschule commented on roles/storage-lead/README.md
> +As an example, if we chose 5, it's rather easy to remove bags from a bucket if we need extra capacity. If we chose 4, a worker leaves, and we don't have anyone that can take over their bucket right a
we instead -to- need to
`to` needed in next comment

2022-01-27 23:53 UTC, traumschule commented on roles/storage-lead/README.md
> +Related to the above, we sometimes need to move bags around. For example when we upgraded to the `giza` network, and content was migrated from the "old" storage system, all bags were assigned to a si
As we don't want **to** rely

2022-01-30 15:34 UTC, traumschule commented
just tested the QN quide. after initial [hickups](https://discord.com/channels/811216481340751934/935463790361837578/937349068252913694) setup works well until https://github.com/bwhm/helpdesk/blob/giza/tools/query-node/README.md#deploy---easy
```
$ query-node/start.sh
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen                                                   
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

$ which docker-compose
/usr/local/bin/docker-compose
$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```
Solved with
> $ sudo usermod -a -G docker myuser
> $ newgrp docker

Next issue: docker claims control over the postgres port but i got one running already.
> $ query-node/start.sh
> ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint db (4c3dc7c45eb5f14ebd600f81b1eb50f5be491411aab83166e6c1fbaa753fc989): Error starting userland proxy: listen tcp4 127.0.0.1:5432: bind: address already in use

Also worth mentioning that YAML does not like tabs :)
> processor                |  289 | →height: "[4191207,4191207]"                 
> processor                | -------^

https://dev.joystreamstats.live/graphql will be synced in a few hours.

2022-01-30 16:59 UTC, bwhm commented
Thanks @traumschule!

I have updated the QN guide, and tested it works. Will review your notes tonight!

2022-01-30 23:05 UTC, bwhm commented
Should have covered the most glaring errors, and added some context.

2022-02-01 05:30 UTC, mnaamani commented on roles/distributors-lead/README.md
> +- if the only operator of a bucket is removed, it's [good practice](#good-practice) to also turn the status and mode off.
"turn the status and mode off." perhaps be more precise about what we mean.
Change accepting bags to "no".

2022-02-01 05:37 UTC, mnaamani commented on roles/distributors-lead/README.md
> +- if there are
```suggestion
```

2022-02-01 05:40 UTC, mnaamani commented on roles/distributors-lead/README.md
> +Currently, we believe most users are located in the eurozone and the CIS. If one were to assume one could only have to families, it *may* make sense to deploy a bucket in the north-eastern parts of t
```suggestion
Currently, we believe most users are located in the eurozone and the CIS. If one were to assume one could only have two families, it *may* make sense to deploy a bucket in the north-eastern parts of the eurozone (eg. Germany or Poland), and one in central Russia. The Former would provide good coverage across the Eurozone and western parts of the CIS, whereas the latter would provide decent coverage across the "rest of" the CIS, and large parts of Asia.
```

2022-02-01 06:00 UTC, mnaamani commented on roles/distributors-lead/README.md
> +Meaning all new bags are uploaded to a single (random) bucket in each family (if they all accept new bags). However, this would obviously mean that the bucket in australia would hold be assigned 5 ti
This statement that australia family is assigned 5x more isn't immediately obvious, maybe I wasn't able to keep clear model of the setup in my head?

2022-02-01 06:01 UTC, mnaamani commented on roles/storage-lead/README.md
> +yarn storage-node leader:set-bucket-limits -i 1 -o 5000 -s 1000000000000 -k /path/to/storage-lead-role-key.json
I think we definitely need to add some support for units when specifying file counts and storage, is there an issue for it?

2022-02-01 06:03 UTC, mnaamani commented on roles/storage-lead/README.md
> +# currently, there is a bug in the storage-node CLI that sets all new buckets created to accept new bags, despite not enabling it (even if no one is invited). therefore, turn it off right away
it would be great to create an issue to address this point in the storage-cli

2022-02-01 06:11 UTC, mnaamani commented on roles/storage-lead/README.md
> +cd /root/joystream/distributor-node/
```suggestion
cd /root/joystream/
```

2022-02-01 06:17 UTC, mnaamani commented on tools/query-node/README.md
> +$ export AT_BLOCK_NUMBER=4191206
Was there a problem exporting at the runtime upgrade block? ..207
from memory no significant events occurred in ..207 other than the runtime update so exporting from prior block is fine.

2022-02-01 08:50 UTC, traumschule commented on tools/query-node/README.md
> +$ export AT_BLOCK_NUMBER=4191206
My QN was fine with the first.

2022-02-01 08:50 UTC, traumschule commented
Just wrote some for the storage lead, maybe it helps.

## bag<>bucket assignment
This query shows which bags are assigned to which provider:

`query { storageBuckets { id createdAt acceptingNewBags dataObjectsSizeLimit dataObjectCountLimit dataObjectsCount dataObjectsSize operatorMetadata { extra nodeEndpoint nodeLocation { countryCode coordinates { latitude longitude } } } bags { id } } }`

You see the initial provider (bucket 0) by JSG holds all bags. Yours (bucket 1) has some newly added videos.
To assign those bags to other providers: https://github.com/bwhm/helpdesk/tree/giza/roles/storage-lead#when-to-update-bags

Instruct bucket 2 to provide a mirror of existing bags:
```
cd ~/joystream # or where your clone is located
for i in $(seq 714 911)
do
    yarn storage-node leader:update-bag -i dynamic:channel:$i -k /path/to/storage-lead-role-key.json -a 2
done
```

## Primitive bucket<>bags stats
Put each snipped in a file:

`get_storage_buckets.sh`
```sh
curl 'https://ipfs.joystreamstats.live/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://ipfs.joystreamstats.live' --data-binary '{"query":"query { storageBuckets {id,createdAt,acceptingNewBags,dataObjectsSizeLimit,dataObjectCountLimit, dataObjectsCount,dataObjectsSize,operatorMetadata{extra,nodeEndpoint,nodeLocation{countryCode,coordinates{latitude,longitude}}}bags{id}}}"}' --compressed > buckets.json
```
`bags-per-bucket.js`
```js
const {data: { storageBuckets }} = require ('./buckets.json')
storageBuckets.sort((a,b)=>a-b).map(b=> console.log(b.id,b.bags.length))
````
The curl command saves the QN reply to `buckets.json`. The script loads it and prints the number of bags per bucket.

Make the first executable and start in a sequence:
```
chmod +x get_storage_buckets.sh
./get_storage_buckets.sh ; node bags.js
0 193
1 6
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
```
A bot would make those updates better formatted and automatically.

2022-02-01 15:07 UTC, bwhm commented on roles/distributors-lead/README.md
> +Meaning all new bags are uploaded to a single (random) bucket in each family (if they all accept new bags). However, this would obviously mean that the bucket in australia would hold be assigned 5 ti
If there are 5 buckets in the families of Europe and Asia, and a new bag will only be held by one of them, this should be true?

2022-02-01 15:07 UTC, bwhm commented on roles/storage-lead/README.md
> +yarn storage-node leader:set-bucket-limits -i 1 -o 5000 -s 1000000000000 -k /path/to/storage-lead-role-key.json
No, but it's a good point.

2022-02-01 15:07 UTC, bwhm commented on roles/storage-lead/README.md
> +# currently, there is a bug in the storage-node CLI that sets all new buckets created to accept new bags, despite not enabling it (even if no one is invited). therefore, turn it off right away
Yeah, I have it on a list :)

2022-02-01 15:08 UTC, bwhm commented on tools/query-node/README.md
> +$ export AT_BLOCK_NUMBER=4191206
Yeah, I'll revert this one!

2022-02-01 18:15 UTC, merged