fixed typo in roles/content-curator-lead/README.md
Joystream/helpdesk pull request #83
Opened 2021-01-13 16:14 UTC by oiclid

2021-02-02 16:28 UTC, bwhm requested changes
Hey @oiclid,

So sorry for the late follow up here, and thank you for contributing! Hope my slowness won't discourage you...

If you don't mind removing the first one, I'll be happy to merge this!

2021-02-02 16:28 UTC, bwhm commented on roles/content-curator-lead/README.md
> +- [Table of Contents](#table-of-contents)
This will not work with the atom package I use to create these ToCs, and it's not that useful to include that, as you are already there :)

2021-02-02 16:28 UTC, bwhm commented on roles/content-curator-lead/README.md
> +Current Group: curators
This one is nice to include!

2021-05-25 08:44 UTC, blrhc commented
Closing due to lack of follow-up, will add the suggested changes in a new PR.

2021-05-25 08:44 UTC, closed without merging