Documentation Improvements
Joystream/helpdesk pull request #88
Opened 2021-03-01 01:24 UTC by nadalfederer

improved docs according to this https://github.com/Joystream/community-repo/issues/87

2021-03-01 10:41 UTC, nadalfederer commented
> Request a review in the forum thread(tbd) from the Admin(tbd).

Seems like I cannot do this. I don't have 100 joy to become a member

> Request a review from @bwhm or @blrhc.

@bwhm

2021-03-02 15:28 UTC, bwhm commented
Hey @nadalfederer,

I'll defer to @blrhc for this, as he usually corrects my mistakes :)
(You have to fix the merge conflicts though)

If you need tokens, please create and share your address!

2021-03-11 06:26 UTC, mochet commented
> > Request a review in the forum thread(tbd) from the Admin(tbd).
> 
> Seems like I cannot do this. I don't have 100 joy to become a member
> 
> > Request a review from @bwhm or @blrhc.
> 
> @bwhm

Hi, you can find the thread to submit corrections here: https://testnet.joystream.org/#/forum/threads/303
If you require tokens you can ask in the Discord server or on here and I'll send you some: https://discord.gg/DE9UN3YpRP

2021-03-12 11:30 UTC, mochet requested changes
I've reviewed this (from the perspective of the bounty/rewards, not judging whether Jsgenesis will accept the changes or not). Please adjust according to my comments and I will submit it for review.

I rejected some stuff since I don't consider them to be substantive changes (such as changing eg. to e.g. -- for most people the meaning of both should be understandable)

Once you have made the changes requested I will put you into the thread and create a spending proposal for rewards: https://testnet.joystream.org/#/forum/threads/303

2021-03-12 11:30 UTC, mochet commented on roles/builders/README.md
> +Because of this, you should regularly monitor the [on-chain forum](https://testnet.joystream.org/#/forum), and the [Community Repo](https://github.com/Joystream/community-repo) to stay updated on the
approved

2021-03-12 11:30 UTC, mochet commented on roles/builders/README.md
> +  - All the above
Unnecessary change.

2021-03-12 11:30 UTC, mochet commented on roles/builders/README.md
> +- `Deadline:` - In some cases, a Community Bounty could have a deadline for when the deliverable must be made. Although Jsgenesis reserves the right not to grade or reward any submissions made after
approved

2021-03-12 11:30 UTC, mochet commented on roles/builders/README.md
> +  - It may be renewed with a new deadline under a different `ID`
approved

2021-03-12 11:30 UTC, mochet commented on roles/builders/README.md
> +As the Council are responsible for establishing the rules, format and workflow, we again advise prospective participants to lookup the specifics for a particular Bounty using the [on-chain forum](htt
approved

2021-03-12 11:30 UTC, mochet commented on roles/content-creators/README.md
> +After the Babylon release, content is no longer managed or consumed with [Pioneer](https://testnet.joystream.org). Viewing content is now done in our new consumer app hosted [here](https://play.joyst
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/content-creators/README.md
> +Follow the instructions. Afterwards, your channel will appear in the [UI](https://play.joystream.org), where you can see if your (optional) banner and avatar looks good.
Unnecessary change, since the user will be prompted with instructions "and" is appropriate.

2021-03-12 11:30 UTC, mochet commented on roles/content-creators/README.md
> +Follow the instructions.
Unnecessary change, since the user will be prompted with instructions "and" is appropriate.

2021-03-12 11:30 UTC, mochet commented on roles/content-creators/README.md
> +Follow the instructions. Afterwards, your video will appear in the [UI](https://play.joystream.org), where you can see if your thumbnail looks good.
Unnecessary change, since the user will be prompted with instructions "and" is appropriate.

2021-03-12 11:30 UTC, mochet commented on roles/content-creators/README.md
> +Follow the instructions.
Unnecessary change, since the user will be prompted with instructions "and" is appropriate.

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +Since the introduction of the proposals' system for the Constantinople testnet, the `Council` has had the power to appoint a `Content Curator Lead` for the network.
this is incorrect, it doesn't look like it needs any change to me

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +Hiring the `Curator Lead` is the responsibility of the `Council` through the proposals' system. Three new proposal types have been introduced to support the hiring process, and more have also been ad
this is incorrect, it doesn't look like it needs any change to me

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +The final step in hiring the `Curator Lead` is to create a `Fill Working Group Leader Opening`. The requirements here are simply to choose the relevant opening from the drop-down menu and choose betw
approved

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +Once a candidate has been chosen, and the final proposal has passed, the focus is now on the new `Curator Lead`...
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +All the useful commands which can be executed by the `Curator Lead` will require the lead to import their "role" key rather than their "member" key. Consequently, in the CLI the `account:import` and
unnecessary change

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +Note that although some values are stated as `u128` or other confusing types, you should provide a plaintext or numbers, and the CLI will convert them for you. Once this command is run, the prompts t
unnecessary change

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +Simply run `working-groups:fillOpening <WGOPENINGID> -g curators` where `<WGOPENINGID>` is the same as earlier, and you will be prompted to select the applicants you wish to hire (using a check-box d
approved

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +Most of the time however, the responsibilities of the `Content Curator Lead` will be very similar to those of a standard `Content Curator`. You can read about these responsibilities in [this section]
rejected the link already works

2021-03-12 11:30 UTC, mochet commented on roles/content-curator-lead/README.md
> +The main task of the `Curators` is curating the content on a chain.
rejected, there is only one chain.

2021-03-12 11:30 UTC, mochet commented on roles/content-curators/README.md
> +- If you attempt to apply with an insufficient stake.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +A "good" Council needs CMs that all have a strong understanding of both the platform's token economics (["tokenomics"](/tokenomics)) and each of the individual Working Groups, and the roles each of t
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +At the end of their term, the KPI payout was USD 300. Half of that is split equally (150/6=25), half is divided by the stake.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +If: `Council Size <= Applicants <= Candidacy Limit`. I.e. the number of applicants is between the `Council Size` and `Candidacy Limit`.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +If: `Candidacy Limit < Applicants`. I.e. the number of applicants is greater than the `Candidacy Limit`.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +All the applicants are sorted and ranked by their stake. The `Announcing` stage ends, and only those with a rank better than, or equal to, the `Candidacy Limit` will proceed to the `Voting` stage.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +If: `Applicants < Council Size`. I.e. the number of applicants is smaller than the `Council Size`.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +When you submit a Vote, a `Random salt` will be generated for you, and only a `Hash` of the vote will be broadcast and stored on a chain. This means:
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +- this means that you if you staked 10k JOY voting a one or more current CMs, and have 5k "free" balance, you can stake 15k for voting
rejected. original and correction are both wrong.

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +At the end of the `Revealing` stage, the applicants are sorted and ranked by their total stake, i.e. the sum of the stake(s) they bonded during the `Announcing` stage, and the sum of all **"revealed"
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +The reason these may not always be present is that the intention is that a Council KPI will be active from the block the Council is elected, until the block a new one replaces them.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +The Council Secretary is an informal role, where the Council themselves are given some flexibility in deciding on compensation and extending their Scope of Work, outside what is defined in the Counci
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +- In some cases, it may make sense to break a Bounty up in to milestones, with partial rewards at each stage. These builds trust as the Council can see the progress being made, and the Assignee can g
rejected/incorrect

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +For a "Free for All", it can be mean reviewing submitted Deliverables as they come in, or waiting for the deadline. How a Submitter should make the CMs aware of their Deliverable once ready (GitHub,
approved

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +Most of the proposals are meant to allow the Council to allocate the platforms resources as efficiently as possible. In order to do so, a [tokenomics spreadsheet](https://docs.google.com/spreadsheets
rejected/both are incorrect

2021-03-12 11:30 UTC, mochet commented on roles/council-members/README.md
> +2. This will provide a view of all the currently active (as well as past) proposals.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-lead/README.md
> +The final step in hiring the `Storage Lead` is to create a `Fill Working Group Leader Opening`. The requirements here simply to choose the relevant opening from the drop-down menu and choose between
approved

2021-03-12 11:30 UTC, mochet commented on roles/storage-lead/README.md
> +Once a candidate has been chosen, and the final proposal has passed, the focus is now on the new `Storage Lead`...
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-lead/README.md
> +All the useful commands which can be executed by the `Storage Lead` will require the lead to import their "role" key rather than their "member" key. Consequently, in the CLI the `account:import` and
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-lead/README.md
> +Note that although some values are stated as `u128` or other confusing types, you should provide a plaintext or numbers, and the CLI will convert them for you. Once this command is run, the prompts t
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-lead/README.md
> +Simply run `working-groups:fillOpening <WGOPENINGID>` where `<WGOPENINGID>` is the same as earlier, and you will be prompted to select the applicants you wish to hire (using a check-box dialog). The
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-lead/README.md
> +As the `Storage Lead` you are responsible for ensuring that `Storage Providers` are performing adequately. They must hold a complete and up-to-date copy of the content directory and ensure the uptime
rejected/incorrect

2021-03-12 11:30 UTC, mochet commented on roles/storage-lead/README.md
> +Within the CLI, all the relevant commands for the Storage Lead can be found through the following query:
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +First, you need to connect to a fully synced [Joystream full node](https://github.com/Joystream/joystream/releases). By default, the program assumes you are running a node on the same device. For ins
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +First, you need to set up `node`, `npm` and `yarn`. This is sometime troublesome to do with the `apt` package manager. Go [here](#install-yarn-and-node-on-linux) to do this if you are not confident i
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +Some default configurations needs to be changed, in order to get better performance:
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +In order to allow for users to upload and download, you have to set up hosting, with an actual domain as both Chrome and Firefox requires `https://`. If you have a "spare" domain or subdomain you don
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +## Install and Set up the Storage Node
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +Go back to [re-install](#install-ipfs).
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +In your browser, find and click on an uploaded media file [here](https://testnet.joystream.org//#/media/), then open the developer console, and find the URL of the asset. Copy the `<content-id>`, i.e
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +(e.g. `5GPhGYaGumtdpFYowMHY15hsdZVZUyEUe2trgh2vq7zGcFKx`)
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/storage-providers/README.md
> +Configure a caddy with `nano ~/Caddyfile` and paste in the following:
rejected/incorrect

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +This page contains all information on how to set up your node and becoming a `Validator` on the Joystream Testnets. It will be updated for improvements, and when something changes for new testnets.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +2. Back in [Pioneer](https://testnet.joystream.org/), click `Validators` in the sidebar, and then the `Account actions` tab.
approved

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +This can be done easily in [Pioneer](https://testnet.joystream.org/)
approved

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +- You have set up a user `joystream` to run the node
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +- You have set up a user `root` to run the node
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +If you don't want to use the default settings, here are some options you can configure.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +1. In [Pioneer](https://testnet.joystream.org/), click `Validators` in the sidebar, and then the `Account actions` tab.
approved

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +1. In [Pioneer](https://testnet.joystream.org/), click `Validators` in the sidebar, and then the `Payouts` tab
approved

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +4. Validator stake (`S_v`) - i.e. the total stake of the `validators` set, corresponding to the sum of the stakes of each `validator`, plus the stake of their [nominators](#nominating) if any. This c
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +At the end of each era, a new set of active validators `V_a` is determined by sorting all those that have declared their intention (e.g. both the active and next up) by their stake, and selecting up
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +If `n` Validators go offline, there will be a two "events" at the end of that `session`:
rejected/both incorrect

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +By selecting the block the event occurred in the [explorer](https://testnet.joystream.org/#/explorer), it will appear like so:
approved

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +These identities which validators are reported "offline".
approved

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +After the transaction has gone through, you will see a new line appearing in the `bonded` column, showing the amount, and a "clock" icon. Hovering over this with your cursor will tell you when your u
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +3. Within 24h, the tokens should be unbonded, and you will see a new line appearing in the `bonded` column, showing the amount you can claim, and a blue "lock" button. Click the button to finalize th
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +  - hovering over the "clock" will show multiple entries, e.g. `<amount>, <time_left>, <block_left>`
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on roles/validators/README.md
> +If `<era_unbonded_n>` >= `<era_current_n>`, you can claim the unbonded funds in step 3.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on testnets/alexandria/README.md
> +After the upgrade, all roles, e.g. `Validators`, `Storage Providers`, `Council Members` and `Curators` were fired from their position.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on testnets/constantinople/README.md
> +After the upgrade, all current roles, i.e. `Storage Providers`, `Council Members` and `Curators` will be fired from their position.
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on tokenomics/README.md
> +  - [Council Members](/roles/council-members) for running and managing the platform's day-to-day operations
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on tokenomics/README.md
> +The sum of the rewards earned will be given directly to the individual Council Members, and those that voted for them, without affecting the overall exchange rate, by topping up the [Fiat Pool](#fiat
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on tokenomics/README.md
> +Assuming again all else being equal, i.e. the only token inflation on the network was the payout for *this* user, the payout stays the same, and our user performs their job satisfactory, they can exp
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on tokenomics/README.md
> +If the user had instead chosen to exchange all their `1,500tJOY` in the first place, they would have locked in a value of `$150 USD`. Their actual choice however, resulted in having cashed in a total
approved

2021-03-12 11:30 UTC, mochet commented on tokenomics/README.md
> +-   The users find that running a Storage Provider costs them `$4 USD per week`
rejected/incorrect

2021-03-12 11:30 UTC, mochet commented on tokenomics/README.md
> +-   The lowest current stake in the pool is `2500 tJOY`
rejected/unnecessary

2021-03-12 11:30 UTC, mochet commented on tokenomics/README.md
> +-   The users find that running a Storage Provider costs them `$1 USD per week`
rejected/unnecessary

2021-03-12 22:50 UTC, closed without merging

2021-03-12 23:14 UTC, nadalfederer commented
I thought it's not about **substantial** but about improving docs according to the dictionary/ using articles appropriately/ punctuations
E.x. - the right way how to write eg. is e.g. so changing it, means improving the docs. https://en.wiktionary.org/wiki/e.g.

2021-03-13 06:50 UTC, mochet commented
> I thought it's not about **substantial** but about improving docs according to the dictionary/ using articles appropriately/ punctuations
> the right way how to write eg. is e.g. so changing it, I thought means improving the docs. https://en.wiktionary.org/wiki/e.g.

Just to clarify I'm a community member, I didn't write the bounty (https://testnet.joystream.org/#/forum/threads/216) I will defer to @bwhm @blrhc to clarify whether some of the changes I rejected are eligible. I did also reject some because they either incorrect or unnecessary. So it may be that my interpretation of the bounty is incorrect.

Regardless, you're still eligible for quite a few rewards with this ($3 per broken link, $2 per grammatical error fix plus any other eligible changes).